---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      age1dpyc7flks4f3j779adqed6zrxmsxmnfxpyvewk6gvt4jwsnfpg3qljuas9
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age1dpyc7flks4f3j779adqed6zrxmsxmnfxpyvewk6gvt4jwsnfpg3qljuas9
