# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:DI9aNVMdjwCpdKzyx+C66MlJMYnRC5e1ztzr9UVEcTZrcWAdqQ==,iv:Ya1bt3WCkLnuOceIRwBCER30C39H8fQ4prqQ2MCjj+I=,tag:0ocHMlTIRPEfDU0NueKpmg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dpyc7flks4f3j779adqed6zrxmsxmnfxpyvewk6gvt4jwsnfpg3qljuas9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNL050eEdna3UzeVZMVW9C
            MG52eTNWaEd6ZmZSRHg4eHpWSDF4a1NhUkc0CnJseDUrbi9GVzZzTHVQWTk4ZVRs
            RmxLVkFwbENhTGFmMk5RalZiaE5aWHcKLS0tIExGTWI1QjhaRHN1Z2l0ZzIxbVJU
            QmtGTEl5RmVrNHVvQzJtaTBxUmRuSDQKUh+7Yby6yfZH2lbf5ojJrlSPfpK3o2ra
            IDkfV7Q7NNWF/e0jABna/Ke5eadryMQjPnrVjkXc7+TW2yLZn9kpgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-13T23:53:20Z"
    mac: ENC[AES256_GCM,data:QW54/mgHhdlAMfWEK/QrBLTsyRbhsfq+SSGtMrntW0vIV5jBozPzSPZzej2Snn3A5jXrF4gj1hwroyuy1SmH6VBQ31SbM3hnZVWh3DKSrGutpWuHNKJUUxVwcFvX9bCkOhKz/HWemr/82RE4B3wb1cCG0AyFAV0ZTTu3BAa1yR4=,iv:VsK5GZiN80vCJwbxifDkI/vCNaMvcBM95mO8G7y28as=,tag:/A/XxAlyBdN3tWoLV9EGpQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
